/**
 * Regenerates Create Game map-type preview SVGs from a 6-player large map.
 * Run: npx tsx scripts/generate-galaxy-previews.ts
 */
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { generateMap } from '../src/game/mapGenerator';
import { GALAXY_SHAPES } from '../src/game/types';

const playerCount = 6;
const planetCount = 35 + (playerCount - 2) * 25;
const gridSide = Math.ceil(Math.sqrt(planetCount * 90));
const seed = 42;

const svgDir = join(process.cwd(), 'assets/galaxy-previews');
const tsPath = join(process.cwd(), 'src/assets/galaxyPreviewSvgs.ts');

function toSvg(
  width: number,
  height: number,
  points: { x: number; y: number }[],
): string {
  const scale = 400 / Math.max(width, height);
  const svgW = (width * scale).toFixed(0);
  const svgH = (height * scale).toFixed(0);
  const dots = points
    .map(
      (p) =>
        `<circle cx="${(p.x * scale).toFixed(1)}" cy="${(p.y * scale).toFixed(1)}" r="2.2" fill="#334"/>`,
    )
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${svgW}" height="${svgH}" viewBox="0 0 ${width * scale} ${height * scale}"><rect width="100%" height="100%" fill="#f5f0eb"/>${dots}</svg>`;
}

mkdirSync(svgDir, { recursive: true });
mkdirSync(join(process.cwd(), 'src/assets'), { recursive: true });

const entries: string[] = [];
for (const shape of GALAXY_SHAPES) {
  const map = generateMap({
    seed,
    width: gridSide,
    height: gridSide,
    planetCount,
    playerCount,
    galaxyShape: shape,
  });
  const svg = toSvg(
    map.width,
    map.height,
    map.planets.map((p) => p.position),
  );
  writeFileSync(join(svgDir, `${shape}.svg`), svg);
  entries.push(`  ${shape}: ${JSON.stringify(svg)},`);
  console.log(`${shape}: ${map.planets.length} planets`);
}

const ts = `/* AUTO-GENERATED by scripts/generate-galaxy-previews.ts — do not edit. */
import type { GalaxyShape } from '../game/types';

export const GALAXY_PREVIEW_SVGS: Record<GalaxyShape, string> = {
${entries.join('\n')}
};
`;
writeFileSync(tsPath, ts);
console.log(`wrote ${GALAXY_SHAPES.length} previews`);
